// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzzujbmkmbkrmobjemyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6enVqYm1rbWJrcm1vYmplbXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjgzOTMsImV4cCI6MjA1NjQ0NDM5M30.JoCCwLUu75x8zEBOBmAxTF5hDym9Rr-QJo1BrJNEdXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);